#! /bin/bash
echo "Uninstalling vms..."

link_target="$HOME"/bin
current_dir=$(cd -P $(dirname "${0}"); pwd)

unlink "${link_target}"/vms.sh
cat "${current_dir}"/install.path | xargs rm -rf
rm -rf "${current_dir}"

echo "Uninstall complete."