#! /bin/bash
echo "Uninstalling vms..."

link_dir="$HOME"/bin
package_dir=$(cd -P $(dirname "${0}"); pwd)

unlink "${link_dir}"/vms
cat "${package_dir}"/install.path | xargs rm -rf
rm -rf "${package_dir}"

echo "Uninstall complete."