#! /bin/bash

if [ -L "${0}" ]; then
    VMS_HOME=$(cd -P $(dirname $(readlink "${0}")); pwd)
else
    VMS_HOME=$(cd -P $(dirname "${0}"); pwd)
fi

. "${VMS_HOME}"/conf/vms.properties
. "${VMS_HOME}"/conf/module.properties
. "${VMS_HOME}"/plugin/vms.sh
. "${VMS_HOME}"/conf/plugins
echo -e "Vertical Management Suite \033[35m${Version}\033[0m, Powered by \033[34m${Author}\033[0m"
echo
while true; do
    wd=$(pwd)
    read -ep $'\033[35m'"[vms-cli ${wd}]# "$'\033[0m' cmd
    vms_main "${cmd}"
    echo
done
